import { types } from "util";

export const regionalForms = {
    // Alolan Forms (Gen 7)
    rattata: {
        formName: "Alolan",
        pokedexId: 10091,
        basePokedexId: 19,
        types: ["dark", "normal"],
    },
    raticate: {
        formName: "Alolan",
        pokedexId: 10093,
        basePokedexId: 20,
        types: ["dark", "normal"],
    },
    raichu: {
        formName: "Alolan",
        pokedexId: 10100,
        basePokedexId: 26,
        types: ["electric", "psychic"],
    },
    sandshrew: {
        formName: "Alolan",
        pokedexId: 10101,
        basePokedexId: 27,
        types: ["ice", "steel"],
    },
    sandslash: {
        formName: "Alolan",
        pokedexId: 10102,
        basePokedexId: 28,
        types: ["ice", "steel"],
    },
    vulpix: {
        formName: "Alolan",
        pokedexId: 10103,
        basePokedexId: 37,
        types: ["ice"],
    },
    ninetales: {
        formName: "Alolan",
        pokedexId: 10104,
        basePokedexId: 38,
        types: ["ice", "fairy"],
    },
    diglett: {
        formName: "Alolan",
        pokedexId: 10105,
        basePokedexId: 50,
        types: ["ground", "steel"],
    },
    dugtrio: {
        formName: "Alolan",
        pokedexId: 10106,
        basePokedexId: 51,
        types: ["ground", "steel"],
    },
    meowth: {
        formName: "Alolan",
        pokedexId: 10107,
        basePokedexId: 52,
        types: ["dark"],
    },
    persian: {
        formName: "Alolan",
        pokedexId: 10108,
        basePokedexId: 53,
        types: ["dark"],
    },
    geodude: {
        formName: "Alolan",
        pokedexId: 10109,
        basePokedexId: 74,
        types: ["rock", "electric"],
    },
    graveler: {
        formName: "Alolan",
        pokedexId: 10110,
        basePokedexId: 75,
        types: ["rock", "electric"],
    },
    golem: {
        formName: "Alolan",
        pokedexId: 10111,
        basePokedexId: 76,
        types: ["rock", "electric"],
    },
    grimer: {
        formName: "Alolan",
        pokedexId: 10112,
        basePokedexId: 88,
        types: ["poison", "dark"],
    },
    muk: {
        formName: "Alolan",
        pokedexId: 10113,
        basePokedexId: 89,
        types: ["poison", "dark"],
    },
    exeggutor: {
        formName: "Alolan",
        pokedexId: 10114,
        basePokedexId: 103,
        types: ["grass", "dragon"],
    },
    marowak: {
        formName: "Alolan",
        pokedexId: 10115,
        basePokedexId: 105,
        types: ["fire", "ghost"],
    },
    articuno: {
        formName: "Galarian",
        pokedexId: 10169,
        basePokedexId: 144,
        types: ["ice", "psychic"],
    },
    zapdos: {
        formName: "Galarian",
        pokedexId: 10170,
        basePokedexId: 145,
        types: ["flying", "fighting"],
    },
    moltres: {
        formName: "Galarian",
        pokedexId: 10171,
        basePokedexId: 146,
        types: ["dark", "flying"],
    },

    // Galarian Forms (Gen 8)
    meowth_galar: {
        formName: "Galarian",
        pokedexId: 10161,
        basePokedexId: 52,
        types: ["steel"],
    },
    ponyta: {
        formName: "Galarian",
        pokedexId: 10162,
        basePokedexId: 77,
        types: ["psychic"],
    },
    rapidash: {
        formName: "Galarian",
        pokedexId: 10163,
        basePokedexId: 78,
        types: ["psychic", "fairy"],
    },
    farfetchd: {
        formName: "Galarian",
        pokedexId: 10166,
        basePokedexId: 83,
        types: ["fighting"],
    },
    weezing: {
        formName: "Galarian",
        pokedexId: 10167,
        basePokedexId: 110,
        types: ["poison", "fairy"],
    },
    slowpoke: {
        formName: "Galarian",
        pokedexId: 10164,
        basePokedexId: 79,
        types: ["psychic"],
    },
    slowbro: {
        formName: "Galarian",
        pokedexId: 10165,
        basePokedexId: 80,
        types: ["psychic", "poison"],
    },
    slowking: {
        formName: "Galarian",
        pokedexId: 10172,
        basePokedexId: 199,
        types: ["poison", "psychic"],
    },
    'mr-mime': {
        formName: "Galarian",
        pokedexId: 10168,
        basePokedexId: 122,
        types: ["ice", "psychic"],
    },
    corsola: {
        formName: "Galarian",
        pokedexId: 10173,
        basePokedexId: 222,
        types: ["ghost"],
    },
    zigzagoon: {
        formName: "Galarian",
        pokedexId: 10174,
        basePokedexId: 263,
        types: ["dark", "normal"],
    },
    linoone: {
        formName: "Galarian",
        pokedexId: 10175,
        basePokedexId: 264,
        types: ["dark", "normal"],
    },
    darumaka: {
        formName: "Galarian",
        pokedexId: 10176,
        basePokedexId: 554,
        types: ["ice"],
    },
    'darmanitan': {
        formName: "Galarian",
        pokedexId: 10177,
        basePokedexId: 555,
        types: ["ice"],
    },
    yamask: {
        formName: "Galarian",
        pokedexId: 10179,
        basePokedexId: 562,
        types: ["ghost", "ground"],
    },
    stunfisk: {
        formName: "Galarian",
        pokedexId: 10180,
        basePokedexId: 618,
        types: ["ground", "steel"],
    },

    // Hisuian Forms (Gen 8 - Legends: Arceus)
    growlithe: {
        formName: "Hisuian",
        pokedexId: 10229,
        basePokedexId: 58,
        types: ["fire", "rock"],
    },
    arcanine: {
        formName: "Hisuian",
        pokedexId: 10230,
        basePokedexId: 59,
        types: ["fire", "rock"],
    },
    voltorb: {
        formName: "Hisuian",
        pokedexId: 10231,
        basePokedexId: 100,
        types: ["electric", "grass"],
    },
    electrode: {
        formName: "Hisuian",
        pokedexId: 10232,
        basePokedexId: 101,
        types: ["electric", "grass"],
    },
    typhlosion: {
        formName: "Hisuian",
        pokedexId: 10233,
        basePokedexId: 157,
        types: ["fire", "ghost"],
    },
    qwilfish: {
        formName: "Hisuian",
        pokedexId: 10234,
        basePokedexId: 211,
        types: ["dark", "poison"],
    },
    sneasel: {
        formName: "Hisuian",
        pokedexId: 10235,
        basePokedexId: 215,
        types: ["fighting", "poison"],
    },
    samurott: {
        formName: "Hisuian",
        pokedexId: 10236,
        basePokedexId: 503,
        types: ["water", "dark"],
    },
    basculin: {
        formName: "Hisuian Red-Striped",
        pokedexId: 10089,
        basePokedexId: 550,
        types: ["water", "rock"],
    },
    basculin_blue: {
        formName: "Hisuian Blue-Striped",
        pokedexId: 10090,
        basePokedexId: 550,
        types: ["water", "dark"],
    },
    zorua: {
        formName: "Hisuian",
        pokedexId: 10238,
        basePokedexId: 570,
        types: ["normal", "ghost"],
    },
    zoroark: {
        formName: "Hisuian",
        pokedexId: 10239,
        basePokedexId: 571,
        types: ["normal", "ghost"],
    },
    decidueye: {
        formName: "Hisuian",
        pokedexId: 10244,
        basePokedexId: 724,
        types: ["grass", "fighting"],
    },
    lilligant: {
        formName: "Hisuian",
        pokedexId: 10237,
        basePokedexId: 549,
        types: ["grass", "fighting"],
    },
    braviary: {
        formName: "Hisuian",
        pokedexId: 10240,
        basePokedexId: 628,
        types: ["psychic", "flying"],
    },
    sliggoo: {
        formName: "Hisuian",
        pokedexId: 10241,
        basePokedexId: 705,
        types: ["steel", "dragon"],
    },
    goodra: {
        formName: "Hisuian",
        pokedexId: 10242,
        basePokedexId: 706,
        types: ["steel", "dragon"],
    },
    avalugg: {
        formName: "Hisuian",
        pokedexId: 10164,
        basePokedexId: 713,
        types: ["ice", "rock"],
    },


    // Paldean Forms (Gen 9)
    tauros: {
        formName: "Paldean Combat Breed",
        pokedexId: 10250,
        basePokedexId: 128,
        types: ["fighting", "normal"],
    },
    tauros_paldean: {
        formName: "Paldean Blaze Breed",
        pokedexId: 10251,
        basePokedexId: 128,
        types: ["fire", "normal"],
    },
    tauros_paldean_water: {
        formName: "Paldean Aqua Breed",
        pokedexId: 10252,
        basePokedexId: 128,
        types: ["water", "normal"],
    },
    wooper: {
        formName: "Paldean",
        pokedexId: 10253,
        basePokedexId: 194,
        types: ["poison", "ground"],
    },
    basculin_paldean: {
        formName: "Paldean",
        pokedexId: 10125,
        basePokedexId: 550,
        types: ["water", "fighting"],
    },

};
